title: LocationSimulator2
description: Spoof locations on physical iPhones and iPads or devices running in iOS Simulator.
url: https://locationsimulator.net
baseurl: ""

markdown: kramdown
permalink: pretty

collections:
  releases:
    output: false

exclude:
  - compose.yaml
  - Gemfile
  - Gemfile.lock
  - README.md
  - script
  - vendor
